name: CI

on: [push, pull_request]

jobs:
  ci:
    name: "Go build"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Test
      run: |
        go mod tidy -v
        go test -v -race ./...

    - run: "go vet ./..."

    - name: Build
      run: go build ./...
